 let ___SCCOBaseRouter: any[] = [
    { path: "/scco/TipoInsumo", component: EK.Modules.SCCO.Pages.TipoInsumo.Vista },
    { path: "/scco/TipoInsumo/:id", component: EK.Modules.SCCO.Pages.TipoInsumo.Edicion },
    { path: "/scco/TipoObra", component: EK.Modules.SCCO.Pages.TipoObra.Vista },
    { path: "/scco/TipoObra/:id", component: EK.Modules.SCCO.Pages.TipoObra.Edicion },
    { path: "/scco/Obra", component: EK.Modules.SCCO.Pages.Obra.Vista },
    { path: "/scco/Obra/:id", component: EK.Modules.SCCO.Pages.Obra.Edicion },
    { path: "/scco/InsumosMateriales", component: EK.Modules.SCCO.Pages.InsumosMateriales.Vista },
    { path: "/scco/InsumosMateriales/:id", component: EK.Modules.SCCO.Pages.InsumosMateriales.Edicion },
    { path: "/scco/GrupoInsumo", component: EK.Modules.SCCO.Pages.GrupoInsumo.Vista },
    { path: "/scco/GrupoInsumo/:id", component: EK.Modules.SCCO.Pages.GrupoInsumo.Edicion },
    { path: "/scco/Contratistas", component: EK.Modules.SCV.Pages.scco.Contratistas.Vista },
    { path: "/scco/Contratistas/:id", component: EK.Modules.SCV.Pages.scco.Contratistas.Edicion },
    { path: "/scco/TipoNivelesPresupuesto", component: EK.Modules.SCCO.Pages.TipoNivelesPresupuesto.Vista },
    { path: "/scco/TipoNivelesPresupuesto/:id", component: EK.Modules.SCCO.Pages.TipoNivelesPresupuesto.Edicion },
    { path: "/scco/Residentes/:id", component: EK.Modules.SCCO.Pages.Residentes.Edicion },
    { path: "/scco/Residentes", component: EK.Modules.SCCO.Pages.Residentes.Vista },
    { path: "/scco/MotivosOrdenesCambio", component: EK.Modules.SCCO.Pages.MotivosOrdenesCambio.Vista },
    { path: "/scco/MotivosOrdenesCambio/:id", component: EK.Modules.SCCO.Pages.MotivosOrdenesCambio.Edicion },
    { path: "/scco/NivelesPresupuesto", component: EK.Modules.SCCO.Pages.NivelesPresupuesto.Vista },
    { path: "/scco/NivelesPresupuesto/:id", component: EK.Modules.SCCO.Pages.NivelesPresupuesto.Edicion },
    { path: "/scco/AnticiposDeducciones", component: EK.Modules.SCCO.Pages.AnticiposDeducciones.Vista },
    { path: "/scco/AnticiposDeducciones/:id", component: EK.Modules.SCCO.Pages.AnticiposDeducciones.Edicion },
    { path: "/scco/AnticiposDeducciones/:id", component: EK.Modules.SCCO.Pages.AnticiposDeducciones.Edicion },
    { path: "/scco/Desarrollos", component: EK.Modules.SCCO.Pages.Desarrollos.Vista },
    { path: "/scco/Desarrollos/:id", component: EK.Modules.SCCO.Pages.Desarrollos.Edicion },
    { path: "/scco/InsumosTarjetas", component: EK.Modules.SCCO.Pages.InsumosTarjetas.Vista },
    { path: "/scco/InsumosTarjetas/:id", component: EK.Modules.SCCO.Pages.InsumosTarjetas.Edicion },
    { path: "/scco/Presupuestos", component: EK.Modules.SCCO.Pages.Presupuestos.Vista },
    { path: "/scco/Presupuestos/:id", component: EK.Modules.SCCO.Pages.Presupuestos.Edicion },
    { path: "/scco/InsumosTarjetas/:id", component: EK.Modules.SCCO.Pages.InsumosTarjetas.Edicion },
    { path: "/scco/TabuladoresInsumos", component: EK.Modules.SCCO.Pages.TabuladoresInsumos.Vista },
    { path: "/scco/TabuladoresInsumos/:id", component: EK.Modules.SCCO.Pages.TabuladoresInsumos.Edicion },
    { path: "/scco/Contratos", component: EK.Modules.SCCO.Pages.Contratos.Vista },
    { path: "/scco/Contratos/:id", component: EK.Modules.SCCO.Pages.Contratos.Edicion }
];

EK.Store.BaseRouter = EK.Store.BaseRouter.concat(___SCCOBaseRouter);