using System.Collections.Generic;
using System.Web.Optimization;

namespace EK.App.App_Start.Bundles
{
    public static class Kontrol
    {
        public static Bundle GetBundle(string version)
        {
            var scripts = new List<string>() {
                 "~/Scripts/modulos/kontrol/Pages/Dashboards.js",
                  "~/Scripts/modulos/kontrol/Pages/HomeEK.js",
                "~/Scripts/modulos/kontrol/Portlets/PortletCliente.js",
                "~/Scripts/modulos/kontrol/Portlets/PortletCompanias.js",
                "~/Scripts/modulos/kontrol/Portlets/PortletCompaniaUsuarioNivel.js",
                "~/Scripts/modulos/kontrol/Portlets/PortletNivelesAsignados.js",
                "~/Scripts/modulos/kontrol/Portlets/PortletClasificadoresAsignados.js",
                "~/Scripts/modulos/kontrol/Portlets/PortletFavoritos.js",
                "~/Scripts/modulos/kontrol/Pages/Admin.js",
                "~/Scripts/modulos/kontrol/Pages/Areas.js",
                "~/Scripts/modulos/kontrol/Pages/Areas-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/blogPost.js",
                "~/Scripts/modulos/kontrol/Pages/BlogPostCategorias.js",
                "~/Scripts/modulos/kontrol/Pages/BlogPostCategorias-Edit.js",
                "~/Scripts/modulos/kontrol/Pages/ConfiguracionFormularios.js",


                //"~/Scripts/modulos/kontrol/Pages/TipoComercializacion.js",
                //"~/Scripts/modulos/kontrol/Pages/TipoComercializacion-Catalogo.js",

                "~/Scripts/modulos/kontrol/Pages/Dashboard.js",
                "~/Scripts/modulos/kontrol/Pages/ConfigurarParametros.js",
                "~/Scripts/modulos/kontrol/Pages/ConfigurarParametros-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/AgrupadorParametros-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/Dominio-Licencia.js",
                "~/Scripts/modulos/kontrol/Pages/Dominio-Editar.js",
                "~/Scripts/modulos/kontrol/Pages/Dominio.js",
                "~/Scripts/modulos/kontrol/Pages/Companias.js",
                "~/Scripts/modulos/kontrol/Pages/Companias-Editar.js",
                "~/Scripts/modulos/kontrol/Pages/TipoFlujoTrabajo.js",
                "~/Scripts/modulos/kontrol/Pages/TipoFlujoTrabajo-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/TipoFlujoTrabajo-Editar.js",
                "~/Scripts/modulos/kontrol/Pages/Usuarios-Nuevo.js",
                "~/Scripts/modulos/kontrol/Pages/FlujoTrabajo-Nuevo.js",
                "~/Scripts/modulos/kontrol/Pages/FlujoTrabajoInstancia.js",
                "~/Scripts/modulos/kontrol/Pages/FlujoTrabajoInstancia-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/FlujoInstancia-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/Usuarios-Editar.js",
                "~/Scripts/modulos/kontrol/Pages/Usuarios.js",
                "~/Scripts/modulos/kontrol/Pages/Usuarios-Excepciones.js",
                "~/Scripts/modulos/kontrol/Pages/Usuarios-Niveles.js",
                "~/Scripts/modulos/kontrol/Pages/Usuarios-Clasificadores.js",
                "~/Scripts/modulos/kontrol/Pages/Usuarios-Agentes.js",
                "~/Scripts/modulos/kontrol/Pages/Niveles.js",
                "~/Scripts/modulos/kontrol/Pages/Niveles-Editar.js",
                "~/Scripts/modulos/kontrol/Pages/Niveles-Configuracion.js",
                "~/Scripts/modulos/kontrol/Pages/TareaInstancia.js",
                "~/Scripts/modulos/kontrol/Pages/Opciones.js",
                "~/Scripts/modulos/kontrol/Pages/Opciones-Nuevo.js",
                "~/Scripts/modulos/kontrol/Pages/Opciones-Editar.js",
                "~/Scripts/modulos/kontrol/Pages/Modulos.js",
                "~/Scripts/modulos/kontrol/Pages/Modulos-Editar.js",
                "~/Scripts/modulos/kontrol/Pages/Parametros.js",
                "~/Scripts/modulos/kontrol/Pages/Parametros-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/ProcessAutorization.js",
                "~/Scripts/modulos/kontrol/Pages/AgrupadorParametros.js",
                "~/Scripts/modulos/kontrol/Pages/Puestos.js",
                "~/Scripts/modulos/kontrol/Pages/Puestos-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/Reportes.js",
                "~/Scripts/modulos/kontrol/Pages/Reportes-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/ReportesVista.js",
                "~/Scripts/modulos/kontrol/Pages/TipoDatos-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/TipoDatos.js",
                "~/Scripts/modulos/kontrol/Pages/Estatus-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/Estatus.js",
                "~/Scripts/modulos/kontrol/Pages/TareaEstatus-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/TareaEstatus.js",
                "~/Scripts/modulos/kontrol/Pages/FlujoEstatus-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/FlujoEstatus.js",
                "~/Scripts/modulos/kontrol/Pages/PlantillasMail.js",
                "~/Scripts/modulos/kontrol/Pages/PlantillasMeta.js",
                "~/Scripts/modulos/kontrol/Pages/PlantillasMetaEdicion.js",
                "~/Scripts/modulos/kontrol/Pages/PlantillasLeads.js",
                "~/Scripts/modulos/kontrol/Pages/PlantillasMail-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/PlantillasLeads-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/UsuarioNivelCompania-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/Clasificadores-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/TiposClasificador.js",
                "~/Scripts/modulos/kontrol/Pages/TiposClasificador-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/Clasificadores-Editar.js",
                "~/Scripts/modulos/kontrol/Pages/TipoMoneda.js",
                "~/Scripts/modulos/kontrol/Pages/TipoMoneda-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/TiposCambio.js",
                "~/Scripts/modulos/kontrol/Pages/TiposCambio-Catalogo.js",
                "~/Scripts/components/workers/WorkerNotifications.js",
                "~/Scripts/modulos/kontrol/Pages/MisProcesos.js",
                "~/Scripts/modulos/kontrol/Pages/MisTareas.js",
                "~/Scripts/modulos/kontrol/Pages/Notificaciones.js",
                "~/Scripts/components/Favoritos.js",
                "~/Scripts/components/NetworkStatus.js",
                "~/Scripts/modulos/kontrol/Pages/CentroCosto.js",
                "~/Scripts/modulos/kontrol/Pages/CentroCosto-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/Citas.js",
                "~/Scripts/modulos/kontrol/Pages/Citas-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/Evento.js",
                "~/Scripts/modulos/kontrol/Pages/Evento-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/TiposEvento.js",
                "~/Scripts/modulos/kontrol/Pages/TiposEvento-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/TareasManuales.js",
                "~/Scripts/modulos/kontrol/Pages/TareasManuales-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/TipoCitas.js",
                "~/Scripts/modulos/kontrol/Pages/TipoCitas-Editar.js",
                "~/Scripts/modulos/kontrol/Pages/GruposUsuario.js",
                "~/Scripts/modulos/kontrol/Pages/GruposUsuario-Editar.js",
                "~/Scripts/modulos/kontrol/Pages/UnidadMedida.js",
                "~/Scripts/modulos/kontrol/Pages/UnidadMedida-Catalogo.js",
                "~/Scripts/modulos/Kontrol/pages/Posicion.js",
                "~/Scripts/modulos/Kontrol/pages/Posicion-Editar.js",
                "~/Scripts/modulos/kontrol/Pages/Vistas.js",
                "~/Scripts/modulos/kontrol/Pages/Vistas-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/PersonalizarCampos/PersonalizarCampos.js",
                "~/Scripts/modulos/kontrol/Pages/PersonalizarCampos/PersonalizarCampos-Editar.js",
                "~/Scripts/modulos/kontrol/Pages/PersonalizarCampos/FieldsAvailable.js",
                 "~/Scripts/modulos/kontrol/Pages/PersonalizarCampos/FieldsRendering.js",
                "~/Scripts/modulos/kontrol/Pages/PersonalizarCampos/personalizarForms-Editar.js",
                 "~/Scripts/modulos/kontrol/Pages/PersonalizarCampos/personalizarForms.js",
                 "~/Scripts/modulos/kontrol/Pages/PullNotificationsActions.js",
                 "~/Scripts/modulos/kontrol/Pages/PullNotificationsActions-Catalogo.js",
                "~/Scripts/modulos/kontrol/Pages/Chat.js",

#if ENK
                "~/Scripts/modulos/kontrol/Pages/Companias/ENK.js",
                "~/Scripts/modulos/kontrol/Pages/Usuarios/ENK.js",
#else
                "~/Scripts/modulos/kontrol/Pages/Companias/Base.js",
                "~/Scripts/modulos/kontrol/Pages/Usuarios/Base.js",
#endif
                "~/Scripts/modulos/kontrol/store/reducers/NotificacionesReducer.js",
                "~/Scripts/modulos/kontrol/store/reducers/HistoryReducer.js",
                "~/Scripts/modulos/kontrol/store/reducers/PosicionesReducer.js",
                "~/Scripts/modulos/kontrol/store/reducers/TipoMonedaReducer.js",
                "~/Scripts/modulos/kontrol/store/reducers/TiposCambioReducer.js",
                "~/Scripts/modulos/kontrol/store/reducers/reducers.js",
                "~/Scripts/modulos/kontrol/Index.js"
#if RUBA
                , "~/Scripts/custom/ruba/modulos/kontrol/Index.js"
#endif
            };

            return new ScriptBundle($"~/b/{version}/modulo-kontrol").Include(scripts.ToArray());
        }
    }
}