let ___KONTROLBaseRouter: any[] = [
    { path: "/", component: EK.Modules.Kontrol.Pages.HomeEK.Vista },
    { path: "/kontrol/DashBoards", component: EK.Modules.Kontrol.Pages.DashBoards.Vista },
    { path: "/kontrol/go/:path", component: EK.UX.Page.PageRedirect },
    { path: "/kontrol/admin", component: EK.Modules.Kontrol.Pages.Admin.Vista },
    { path: "/kontrol/dominios", component: EK.Modules.Kontrol.Pages.Dominios.Vista },
    { path: "/kontrol/dominios/:id", component: EK.Modules.Kontrol.Pages.Dominios.Edicion },
    { path: "/kontrol/dominios/licencias/:id", component: EK.Modules.Kontrol.Pages.Dominios.Licencias },
    //{ path:"/kontrol/clientes/:id", component:EK.Modules.Kontrol.Pages.PageVerCliente},
    { path: "/kontrol/citas", component: EK.Modules.Kontrol.Pages.Citas.Vista },
    { path: "/kontrol/citas/:id", component: EK.Modules.Kontrol.Pages.Citas.Edicion },
    { path: "/kontrol/tipoCitas", component: EK.Modules.Kontrol.Pages.TipoCitas.Vista },
    { path: "/kontrol/tipoCitas/:id", component: EK.Modules.Kontrol.Pages.TipoCitas.Edicion },
    { path: "/kontrol/eventos", component: EK.Modules.Kontrol.Pages.Eventos.Edicion },
    { path: "/kontrol/eventos/:id", component: EK.Modules.Kontrol.Pages.Eventos.Edicion },
    { path: "/kontrol/tiposEvento", component: EK.Modules.Kontrol.Pages.TiposEvento.Edicion },
    { path: "/kontrol/tiposEvento/:id", component: EK.Modules.Kontrol.Pages.TiposEvento.Edicion },

    { path: "/kontrol/BlogPostCategorias", component: EK.Modules.Kontrol.Pages.BlogPostCategorias.Vista },
    { path: "/kontrol/BlogPostCategorias/:id", component: EK.Modules.Kontrol.Pages.BlogPostCategorias.Edicion },

    { path: "/kontrol/configuracionFormulario", component: EK.Modules.Kontrol.Pages.ConfiguracionFormularios.Vista },

    //{ path: "/kontrol/tipoComercializacion", component: EK.Modules.Kontrol.Pages.TipoComercializacion.Vista },
    //{ path: "/kontrol/tipoComercializacion/:id", component: EK.Modules.Kontrol.Pages.TipoComercializacion.Edicion },
    { path: "/kontrol/UnidadMedida", component: EK.Modules.Kontrol.Pages.UnidadMedidanm.Vista },
    { path: "/kontrol/UnidadMedida/:id", component: EK.Modules.Kontrol.Pages.UnidadMedidanm.Edicion },
    { path: "/kontrol/gruposUsuario", component: EK.Modules.Kontrol.Pages.GruposUsuario.Vista },
    { path: "/kontrol/gruposUsuario/:id", component: EK.Modules.Kontrol.Pages.GruposUsuario.Edicion },

    { path: "/kontrol/tareas", component: EK.Modules.Kontrol.Pages.TareasManuales.Vista },
    { path: "/kontrol/tareas/:id", component: EK.Modules.Kontrol.Pages.TareasManuales.Edicion },
    { path: "/kontrol/tareasRapidas", component: EK.Modules.Kontrol.Pages.TareasManuales.TareasRapidas },
    { path: "/kontrol/tareasRapidas/:id", component: EK.Modules.Kontrol.Pages.TareasManuales.TareasRapidas },

    { path: "/kontrol/companias", component: EK.Modules.Kontrol.Pages.Companias.Vista },
    //{ path:"/kontrol/companias/nuevo", component:EK.Modules.Kontrol.Pages.NuevaCompania}, 
    { path: "/kontrol/companias/:id", component: EK.Modules.Kontrol.Pages.Companias.Edicion },
    { path: "/kontrol/workflows/tipos", component: EK.Modules.Kontrol.Pages.TiposFlujo.Vista },
    { path: "/kontrol/workflows/tipos/:id", component: EK.Modules.Kontrol.Pages.TiposFlujo.Edicion },

    //{ path: "/kontrol/workflows/plantilla/nuevo", component: EK.Modules.Kontrol.Pages.NuevoFlujo }, 
    //{ path: "/kontrol/autorizaciones/:id", component: EK.Modules.Kontrol.Pages.Autorizaciones.Edicion }, 
    { path: "/kontrol/autorizaciones/:id", component: EK.Modules.Kontrol.Pages.Autorizaciones.Vista },
    { path: "/kontrol/usuarios", component: EK.Modules.Kontrol.Pages.Usuarios.Vista },
    { path: "/kontrol/usuarios/:id", component: EK.Modules.Kontrol.Pages.Usuarios.Edicion },
    { path: "/kontrol/usuarios/password/:id", component: EK.Modules.Kontrol.Pages.Usuarios.ChangePassword },
    { path: "/kontrol/usuarios/clasificadores/:id", component: EK.Modules.Kontrol.Pages.Usuario$Clasificadores },
    //{ path: "/kontrol/usuarios/niveles/:id", component: EK.Modules.Kontrol.Pages.Usuario$Niveles }, 
    { path: "/kontrol/usuarios/excepciones/:id", component: EK.Modules.Kontrol.Pages.Usuario$Excepciones },
    { path: "/kontrol/usuarios/agentes/:id", component: EK.Modules.Kontrol.Pages.Usuarios.Agente },
    { path: "/kontrol/niveles", component: EK.Modules.Kontrol.Pages.Niveles.Vista },
    { path: "/kontrol/niveles/:id", component: EK.Modules.Kontrol.Pages.Niveles.Edicion },
    { path: "/kontrol/centrocosto", component: EK.Modules.Kontrol.Pages.CentroCosto.Vista },
    { path: "/kontrol/centrocosto/:id", component: EK.Modules.Kontrol.Pages.CentroCosto.Edicion },

    { path: "/kontrol/posiciones", component: EK.Modules.Kontrol.Pages.Posiciones.Vista },
    { path: "/kontrol/NotFoundItem", component: NotFoundItem },
    { path: "/kontrol/posiciones/:id", component: EK.Modules.Kontrol.Pages.Posiciones.Edicion },

    //{ path:"/kontrol/niveles/configuracion/:id", component:EK.Modules.Kontrol.Pages.Niveles.Nivel$Configuracion},
    { path: "/kontrol/workflows/procesos", component: EK.Modules.Kontrol.Pages.FlujoTrabajoInstancia.Vista },
    { path: "/kontrol/workflows/misprocesos", component: EK.Modules.Kontrol.Pages.FlujoTrabajoInstancia.VistaMe },
    { path: "/kontrol/workflows/procesos/:id", component: EK.Modules.Kontrol.Pages.FlujoTrabajoInstancia.Edicion },
    //{ path: "/kontrol/workflows/plantilla/tarea/:id", component: EK.Modules.Kontrol.Pages.PageViewTaskInstance },
    //{ path: "/kontrol/workflows/tarea/nuevo", component: EK.Modules.Kontrol.Pages.PageAddTask },
    //{ path: "/kontrol/workflows/tarea/:id", component: EK.Modules.Kontrol.Pages.PageEditTask },
    //{ path: "/kontrol/workflows/plantilla", component: EK.Modules.Kontrol.Pages.FlujoTrabajoListPage },
    { path: "/kontrol/modulos", component: EK.Modules.Kontrol.Pages.Modulos.Vista },
    { path: "/kontrol/modulos/:id", component: EK.Modules.Kontrol.Pages.Modulos.Edicion },
    //{ path: "/kontrol/opciones", component: EK.Modules.Kontrol.Pages.OpcionesPage },
    { path: "/kontrol/opciones/nuevo", component: EK.Modules.Kontrol.Pages.NuevaOpcion },
    { path: "/kontrol/opciones/:id", component: EK.Modules.Kontrol.Pages.PageOpcionesCatalogo },
    { path: "/kontrol/parametros/plantillas", component: EK.Modules.Kontrol.Pages.Parametros.Vista },
    { path: "/kontrol/parametros/:id", component: EK.Modules.Kontrol.Pages.Parametros.Edicion },
    //{ path: "/kontrol/parametros/configuracion", component: EK.Modules.Kontrol.Pages.configurarParametrosPage },
    //{ path: "/kontrol/parametros/configuracion/:id", component: EK.Modules.Kontrol.Pages.PageConfigurarParametroCatalogo },
    { path: "/kontrol/workflows/autorizacion/:id", component: EK.Modules.Kontrol.Pages.PageProcesoAutorizacion },
    //{ path: "/kontrol/workflows/misprocesos", component: EK.Modules.Kontrol.Pages.MisProcesos },
    { path: "/kontrol/workflows/mistareas", component: EK.Modules.Kontrol.Pages.FlujoTrabajoInstancia.TareasInstancia},
    //{ path: "/kontrol/parametros/secciones", component: EK.Modules.Kontrol.Pages.SeccionesParametrosPage },
    //{ path: "/kontrol/parametros/secciones/nuevo", component: EK.Modules.Kontrol.Pages.NuevaSeccionParametro },
    //{ path: "/kontrol/parametros/secciones/:id", component: EK.Modules.Kontrol.Pages.PageSeccionesParametrosCatalogo },
    { path: "/kontrol/parametros", component: EK.Modules.Kontrol.Pages.Parametros.Vista },

    { path: "/kontrol/puestos", component: EK.Modules.Kontrol.Pages.Puestos.Vista },
    { path: "/kontrol/puestos/:id", component: EK.Modules.Kontrol.Pages.Puestos.Edicion },
    //{ path: "/kontrol/tiposdatos", component: EK.Modules.Kontrol.Pages.TipoDatosPage },
    { path: "/kontrol/tiposdatos/nuevo", component: EK.Modules.Kontrol.Pages.Nuevotipodato },
    { path: "/kontrol/tiposdatos/:id", component: EK.Modules.Kontrol.Pages.PagetipodatosCatalogo },
    { path: "/kontrol/estatus", component: EK.Modules.Kontrol.Pages.Estatus.Vista },
    { path: "/kontrol/estatus/:id", component: EK.Modules.Kontrol.Pages.Estatus.Edicion },
    { path: "/kontrol/tareaestatus", component: EK.Modules.Kontrol.Pages.TareaEstatus.Vista },
    { path: "/kontrol/tareaestatus/:id", component: EK.Modules.Kontrol.Pages.TareaEstatus.Edicion },
    { path: "/kontrol/flujoestatus", component: EK.Modules.Kontrol.Pages.FlujoEstatus.Vista },
    { path: "/kontrol/flujoestatus/:id", component: EK.Modules.Kontrol.Pages.FlujoEstatus.Edicion },
    { path: "/kontrol/plantillas", component: EK.Modules.Kontrol.Pages.Plantillas.Vista },
    { path: "/kontrol/plantillasmeta", component: EK.Modules.Kontrol.Pages.PlantillasMeta.Vista },
    { path: "/kontrol/plantillasmeta/:id", component: EK.Modules.Kontrol.Pages.PlantillasMeta.Edicion },
    { path: "/kontrol/PlantillasLeads", component: EK.Modules.Kontrol.Pages.PlantillasLeads.Vista },
    //{ path:"/kontrol/plantillas/nuevo", component:EK.Modules.Kontrol.Pages.NuevoPlantillasMails}, 
    { path: "/kontrol/plantillas/:id", component: EK.Modules.Kontrol.Pages.Plantillas.Edicion },
    { path: "/kontrol/PlantillasLeads/:id", component: EK.Modules.Kontrol.Pages.PlantillasLeads.Edicion },
    { path: "/kontrol/notificaciones/:id", component: EK.Modules.Kontrol.Pages.Notificaciones.Vista },
    //{ path: "/kontrol/notificaciones/:id", component: EK.Modules.Kontrol.Pages.PageVerNotificaciones },
    { path: "/kontrol/tiposClasificador", component: EK.Modules.Kontrol.Pages.TiposClasificador.Vista },
    { path: "/kontrol/tiposClasificador/:id", component: EK.Modules.Kontrol.Pages.TiposClasificador.Edicion },
    { path: "/kontrol/monedas", component: EK.Modules.Kontrol.Pages.Monedas.Vista },
    { path: "/kontrol/monedas/:id", component: EK.Modules.Kontrol.Pages.Monedas.Edicion },
    //{ path: "/kontrol/tiposcambio", component: EK.Modules.Kontrol.Pages.TiposCambio.Consulta },
    //{ path: "/kontrol/tiposcambio/nuevo", component: EK.Modules.Kontrol.Pages.TiposCambio.Nuevo },
    //{ path: "/kontrol/tiposcambio/:id", component: EK.Modules.Kontrol.Pages.TiposCambio.Edicion },
    { path: "/kontrol/areasOrganizacion", component: EK.Modules.Kontrol.Pages.Areas.Vista },
    { path: "/kontrol/areasOrganizacion/:id", component: EK.Modules.Kontrol.Pages.Areas.Edicion },
    { path: "/kontrol/gis/vistas", component: EK.Modules.Kontrol.Pages.Vistas.Vista },
    { path: "/kontrol/gis/vistas/:id", component: EK.Modules.Kontrol.Pages.Vistas.Edicion },
    { path: "/kontrol/reportes", component: EK.Modules.Kontrol.Pages.Reportes.Vista },
    { path: "/kontrol/reportes/:id", component: EK.Modules.Kontrol.Pages.Reportes.Edicion },
    { path: "/kontrol/reportes/ver/:id", component: EK.Modules.Kontrol.Pages.Reportes.VistaReporte },
    { path: "/kontrol/PersonalizarCampos", component: EK.Modules.Kontrol.Pages.PersonalizarCampos.Vista },
    { path: "/kontrol/PersonalizarCampos/:id", component: EK.Modules.Kontrol.Pages.PersonalizarCampos.Edicion },
    { path: "/kontrol/PersonalizarForms", component: EK.Modules.Kontrol.Pages.PersonalizarForms.Edicion },
    //{ path: "/kontrol/PersonalizarForms/:id", component: EK.Modules.Kontrol.Pages.PersonalizarForms.Edicion },
    { path: "/kontrol/PullNotificationsActions", component: EK.Modules.Kontrol.Pages.PullNotificationsActions.Vista },
    { path: "/kontrol/PullNotificationsActions/:id", component: EK.Modules.Kontrol.Pages.PullNotificationsActions.Edicion },


    //{ path: "/kontrol/Chat", component: EK.Modules.Kontrol.Pages.Chat.Vista },
];

EK.Store.BaseRouter = EK.Store.BaseRouter.concat(___KONTROLBaseRouter);