let scvReducers = {
    caracteristicasComponent: EK.Store.SCV.Reducers.caracteristicasComponentReducer,
    categorias: EK.Store.SCV.Reducers.CategoriasReducer,
    mediosPublicidad: EK.Store.SCV.Reducers.mediosPublicidadReducer,
    estatusubicacion: EK.Store.SCV.Reducers.EstatusUbicacionReducer,
    gradosInteres: EK.Store.SCV.Reducers.GradosInteresReducer,
    modelosPaquete: EK.Store.SCV.Reducers.modelosPaqueteReducer,
    tipoinmueble: EK.Store.SCV.Reducers.TipoInmuebleReducer,
    tipofinanciamiento: EK.Store.SCV.Reducers.tipoFinanciamientoReducer,
    tiposUbicacion: EK.Store.SCV.Reducers.tiposUbicacionReducer,
    etapas: EK.Store.SCV.Reducers.EtapasReducer,
    campaniaPublicidad: EK.Store.SCV.Reducers.campaniaPublicidadReducer,
    referenciasPersonales: EK.Store.SCV.Reducers.referenciasPersonalesReducer,
    rangosIngresos: EK.Store.SCV.Reducers.rangosIngresosReducer,
    segmentos: EK.Store.SCV.Reducers.segmentosReducer,
    segmentosvigencias: EK.Store.SCV.Reducers.SegmentosVigenciasReducer,
    instituciones: EK.Store.SCV.Reducers.InstitucionesReducer,
    svclientes: EK.Store.SCV.Reducers.ScvclientesReducer,
    empresas: EK.Store.SCV.Reducers.empresasReducer,
    motivoscancelacion: EK.Store.SCV.Reducers.ScvmotivosCancelacionReducer,
    puntosventa: EK.Store.SCV.Reducers.ScvpuntosVentaReducerManager,
    prototipos: EK.Store.SCV.Reducers.PrototiposReducer,
    tiposCaracteristica: EK.Store.SCV.Reducers.tiposCaracteristicaAdicionalReducer,
    caracteristicaAdicional: EK.Store.SCV.Reducers.caracteristicaAdicionalReducer,
    desarrollos: EK.Store.SCV.Reducers.ScvdesarrollosReducerManager,
    ubicaciones: EK.Store.SCV.Reducers.ubicacionesReducer,
    estatusExpediente: EK.Store.SCV.Reducers.estatusExpedienteReducer,
    sindicatos: EK.Store.SCV.Reducers.sindicatosReducer,
    centralesObreras: EK.Store.SCV.Reducers.centralesObrerasReducer,
    notarios: EK.Store.SCV.Reducers.ScvnotariosReducerManager,
    planesPagos: EK.Store.SCV.Reducers.planesPagosReducer,
    conceptosPago: EK.Store.SCV.Reducers.conceptosPagoReducer,
    ventas: EK.Store.SCV.Reducers.ScvventasReducerManager,
    listaPrecios: EK.Store.SCV.Reducers.listaPreciosReducer,
    requisitos: EK.Store.SCV.Reducers.requisitosReducer,
    documentosExpediente: EK.Store.SCV.Reducers.documentosExpedienteReducer,
    esquemas: EK.Store.SCV.Reducers.esquemasReducer,
    procesosReducer: EK.Store.SCV.Reducers.procesosObjReducer,
    seguimientosReducer: EK.Store.SCV.Reducers.seguimientosObjReducer,
    comisionesReducer: EK.Store.SCV.Reducers.comisionesObjReducer,
    fasesExpediente: EK.Store.SCV.Reducers.fasesExpedienteReducer,
    expedientes: EK.Store.SCV.Reducers.expedientesReducer,
    coordReducer: EK.Store.SCV.Reducers.coordenadasReducer
}

EK.Store.BaseReducers = EK.Global.assign(EK.Store.BaseReducers, scvReducers);