let ___SBOBaseRouter: any[] = [
    //{ path: "/sbo/", component: EK.Modules.SBO.Pages.BancosPage },
    //{ path: "/sbo/bancos", component: EK.Modules.SBO.Pages.BancosPage },
    //{ path: "/sbo/bancos/nuevo", component: EK.Modules.SBO.Pages.NuevoBanco },
    //{ path: "/sbo/bancos/:id", component: EK.Modules.SBO.Pages.PageBancosCatalogo },
    //{ path: "/sbo/tipomovimiento", component: EK.Modules.SBO.Pages.TipoMovimientoPage },
    //{ path: "/sbo/tipomovimiento/nuevo", component: EK.Modules.SBO.Pages.NuevoTipoMovimiento },
    //{ path: "/sbo/tipomovimiento/:id", component: EK.Modules.SBO.Pages.PageTipoMovimientoCatalogo },
    //{ path: "/sbo/tipomovimiento/clasificadores/:id", component: EK.Modules.SBO.Pages.TM$Clasificadores },
    //{ path: "/sbo/cuentasbancarias", component: EK.Modules.SBO.Pages.CuentasBancariasPage },
    //{ path: "/sbo/cuentasbancarias/nuevo", component: EK.Modules.SBO.Pages.NuevoCuentaBancaria },
    //{ path: "/sbo/cuentasbancarias/:id", component: EK.Modules.SBO.Pages.PageCuentaBancariaCatalogo },
    //{ path: "/sbo/cuentasbancarias/clasificadores/:id", component: EK.Modules.SBO.Pages.CB$Clasificadores },
    //{ path: "/sbo/subtipomovimiento", component: EK.Modules.SBO.Pages.SubTipoMovimientoPage },
    //{ path: "/sbo/subtipomovimiento/nuevo", component: EK.Modules.SBO.Pages.NuevoSTipoMovimiento },
    //{ path: "/sbo/subtipomovimiento/:id", component: EK.Modules.SBO.Pages.PageSTipoMovimientoCatalogo },
    { path: "/sbo/reportes/cheques", component: EK.Modules.SBO.Reportes.ReporteDetalladoCheques },
    //{ path: "/sbo/procesos/capturacheque", component: EK.Modules.SBO.Pages.CapturaChequePage },
    { path: "/sbo/procesos/capturacheque/nuevo", component: EK.Modules.SBO.Pages.NuevoCheque },
    { path: "/sbo/procesos/capturacheque/:id", component: EK.Modules.SBO.Pages.PageChequeCatalogo },
    { path: "/sbo/procesos/capturacheque/nuevo", component: EK.Modules.SBO.Pages.NuevoCheque },
    //{ path: "/sbo/procesos/batch", component: EK.Modules.SBO.Pages.BatchPage },
    { path: "/sbo/procesos/batch/confirmacion", component: EK.Modules.SBO.Pages.ConfirmacionBatchPage },
    { path: "/sbo/procesos/generacionpagos/chequesautomaticos", component: EK.Modules.SBO.Pages.GeneracionChequesAutomaticosPage },
    { path: "/sbo/procesos/generacionpagos/chequesautomaticos/confirmacionpagos", component: EK.Modules.SBO.Pages.ConfirmacionPagosPage },
    //{ path: "/sbo/procesos/generacionpagos/batch", component: EK.Modules.SBO.Pages.BatchPage },
    { path: "/sbo/procesos/generacionpagos/batch/confirmacion", component: EK.Modules.SBO.Pages.ConfirmacionBatchPage },
];

EK.Store.BaseRouter = EK.Store.BaseRouter.concat(___SBOBaseRouter);