let kontrolReducers = {
    app: EK.Store.Reducers.AppReducer,
    kontrolFileManager: EK.Store.Reducers.KontrolFileManagerReducer,
    clasificadores: EK.Store.Reducers.ClasificadoresReducer,
    clientes: EK.Store.Reducers.ClientesReducer,
    companias: EK.Store.Reducers.CompaniasReducer,
    configurarparametros: EK.Store.Reducers.ConfigurarParametrosReducer,
    dropdownlistdata: EK.Store.Reducers.DropDownListReducer,
    estatus: EK.Store.Reducers.EstatusReducer,
    flujos: EK.Store.Reducers.WorkflowsReducer,
    flujoestatus: EK.Store.Reducers.FlujoEstatusReducer,
    flujoInstancias: EK.Store.Reducers.WorkflowInstancesReducer,
    forms: EK.Store.Reducers.FormReducer,
    global: EK.Store.Reducers.GlobalReducer,
    history: EK.Store.Reducers.HistoryReducer,
    modulos: EK.Store.Reducers.ModulosReducer,
    niveles: EK.Store.Reducers.NivelesReducer,
    notifications: EK.Store.Reducers.NotificationReducer,
    notificaciones: EK.Store.Reducers.NotificacionesReducer,
    opciones: EK.Store.Reducers.OpcionesReducer,
    parametros: EK.Store.Reducers.ParametrosReducer,
    plantillas: EK.Store.Reducers.PlantillasReducer,
    posiciones: EK.Store.Reducers.PosicionesReducer,
    //puestos: EK.Store.Reducers.PuestosReducer,
    secciones: EK.Store.Reducers.seccionesParametrosReducer,
    tareaestatus: EK.Store.Reducers.TareaEstatusReducer,
    usuarios: EK.Store.Reducers.UsuariosReducer,
    tiposdatos: EK.Store.Reducers.TipoDatosReducer,
    tipomoneda: EK.Store.KONTROL.Reducers.TipoMonedaReducer,
    TiposCambioReducer: EK.Store.KONTROL.Reducers.TiposCambioReducer,
}

EK.Store.BaseReducers = EK.Global.assign(EK.Store.BaseReducers, kontrolReducers);